### PR TITLE
Allow upgrading pip; also yb_activate_virtualenv should fail if pip install fails

### PR DESCRIPTION
**Pull request by mbautin**

### CODE REVIEW

**Comment by svarnau** [comment]
The code looks fine, but I don't understand the usage model. Why would I want to do a single update and then never again? I can understand only once per run of a tool (in case common gets included in multiple places), or only if the last update was  certain amount of time past (last updated more than a day ago).

**Review by svarnau — APPROVED** [review]
LGTM

**Comment by jharveysmith** [comment]
Why not just upgrade pip unconditionally after creating the venv?

**Comment by mbautin** [comment]
I would like to avoid forcing a pip upgrade, and only enable it when it is necessary. In many cases the installed version of pip will be sufficient.

**Pull request merged**
